services:
  - type: worker
    name: rocketchat-customgpt-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    autoDeploy: false