version: '3.8'

services:
  bot:
    build: .
    container_name: customgpt-discord-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: bot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bot-network

volumes:
  redis-data:

networks:
  bot-network:
    driver: bridge